/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgenciesRouteImport } from './routes/_authenticated/agencies'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLogisticsRouteImport } from './routes/_authenticated/logistics'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgenciesRoute = AuthenticatedAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogisticsRoute = AuthenticatedLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agencies': typeof AuthenticatedAgenciesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agencies': typeof AuthenticatedAgenciesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agencies': typeof AuthenticatedAgenciesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/logistics': typeof AuthenticatedLogisticsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agencies'
    | '/dashboard'
    | '/logistics'
    | '/staff'
    | '/requests/new'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agencies'
    | '/dashboard'
    | '/logistics'
    | '/staff'
    | '/requests/new'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agencies'
    | '/_authenticated/dashboard'
    | '/_authenticated/logistics'
    | '/_authenticated/staff'
    | '/_authenticated/requests/new'
    | '/_authenticated/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agencies': {
      id: '/_authenticated/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AuthenticatedAgenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics': {
      id: '/_authenticated/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgenciesRoute: typeof AuthenticatedAgenciesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogisticsRoute: typeof AuthenticatedLogisticsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgenciesRoute: AuthenticatedAgenciesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogisticsRoute: AuthenticatedLogisticsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
